<?php require('template/header.phtml') ?>


<h2>Login: </h2>

<div>
    <form id="loginFormm" action=""<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <label for="email">Email</label><br>
        <input  type="email" name="email" required><br>
        <label for="pass">Password</label><br>
        <input  type="password" name="pass" required><br>
        <button type="submit" name="submit ">Submit</button><br>
        <a href="signUp.php">Sign Up</a>
    </form>
</div>

<?php require('template/footer.phtml')?>