<?php require('template/header.phtml') ?>

<h3> Sign Up: </h3> 
<div>
    <form id="signUp" action=""<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
    
    <label for="username">Username:</label><br>
    <input type="text" id="username" name="username" required><br>

    <label for="email">Email:</label><br>
    <input type="email" id="email" name="email" required><br>

    <label for="password">Password:</label><br>
    <input type="password" id="password" name="password" required><br>

    <label for="role">Role:</label><br>
    <select id="role" name="role" required><br>
      <option value="">--Select Role--</option>
      <option value="homeowner">Homeowner</option>
      <option value="user">User</option>
    </select><br>

    <label for="firstname">First Name:</label><br>
    <input type="text" id="firstname" name="firstname" required><br>

    <label for="lastname">Last Name:</label><br>
    <input type="text" id="lastname" name="lastname" required><br>

    <button type="submit">Sign Up</button><br>
            <a href="login.php">login</a>

  </form>
</div>

<?php require('template/footer.phtml') ?>

