<?php require('template/header.phtml') ?>


<!-- Page content -->
<section class="py-5">
  <div class="container px-5">

    <!-- SingUp Form Section -->
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <div class="feature d-flex align-items-center justify-content-center bg-primary bg-gradient text-white mb-3"><i class="bi bi-box-arrow-in-right fs-1"></i></div>
        <h2 class="fw-bolder">Sign Up:</h2>
        <?php if (!empty($view->message)) : ?>
        <div class="alert alert-info text-center mt-3"><?= htmlspecialchars($view->message) ?></div>
     <?php endif; ?>
        <p class="lead fw-normal text-muted mb-0">Create your account</p>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-6">      
    <form id="signUp" action=""<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        
        <div class="form-floating mb-3">
              <input class="form-control" id="username" name="username" type="text" placeholder="Enter your  username..." data-sb-validations="required" />
              <label for="name">Username:</label>
              <div class="invalid-feedback" data-sb-feedback="username:required">A username is required.</div>
        </div>
        
        <div class="form-floating mb-3">
            <input class="form-control" id="name" name="name" type="text" placeholder="Enter your First name..." />
            <label for="name">Name:</label>
        </div>
    
   <div class="form-floating mb-3">
              <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
              <label for="email">Email</label>
            </div>
        
    <div class="form-floating mb-3">
              <input type="password" class="form-control" name="pass" id="pass" placeholder="Password" required>
              <label for="pass">Password</label>
            </div>
        
        
    <div class="form-floating mb-3">
      <select class="form-select" id="role" name="role" required>
            <option value="">--Select Role--</option>
            <option value="Homeowner">Homeowner</option>
            <option value="User">User</option>
      </select>
        <label for="role">Role</label>
      <div class="invalid-feedback" data-sb-feedback="role:required">Please select a role.</div>
    </div>
    <div class="d-grid mb-3">
        <button type="submit"type="submit" name="submit" class="btn btn-primary btn-lg">Sign Up</button><br>
    </div>
    
    <div class="text-center">
            <a href="login.php">Do you have an account? login</a>
    </div>
  </form>
    </div>
    </div>
    </div>
    </div>
    
</section>

<?php require('template/footer.phtml') ?>