<?php if (!empty($view->chargePoints)): ?>

      <?php foreach ($filteredPoints as $point): ?>
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image -->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details -->
            <div class="card-body p-4">
              <div class="text-center">
                <h5 class="fw-bolder"><?= $point->getAddress() ?></h5>
                 <?= $point->getPrice() ?> BHD

              </div>
            </div>
            <!-- Product actions -->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <a href="#" class="btn btn-outline-dark mt-auto"
                 onclick="openBookingModal(<?= $point->getId() ?>)">Book</a>
                  <a href="Booking.php?view=contact" class="btn btn-secondary">Contact Home Owner</a>
              </div>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
        
        <?php endif; ?>