<?php require('Views/template/header.phtml') ?>

<!-- Homeowner Dashboard Header -->
<header class="bg-dark py-5">
    <div class="container px-5" id="welcome-section">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2"> User Dashboard</h1>
                    <p class="lead fw-normal text-white-50 mb-4">
                        Book your chargepoint based on your requirment.
                    </p>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                <img class="img-fluid rounded-3 my-5" src="https://dummyimage.com/600x400/343a40/6c757d" alt="EV Charging"/>
            </div>
        </div>
    </div>
</header>

<!-- Dashboard Features Section -->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h2 class="fw-bolder mb-0">Your Tools</h2>
                <span class="text-muted fs-6">All-in-one panel to book your charging point</span>
            </div>
            <div class="col-lg-8">
                <div class="row gx-5 row-cols-1 row-cols-md-2">
                    <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-geo-alt-fill"></i></div>
                        <h2 class="h5">Book Charge Point</h2>
                        <p class="mb-0">Book a charge point for your reason.</p>
                    </div>
                    <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-calendar-check"></i></div>
                        <h2 class="h5">View History Booking</h2>
                        <p class="mb-0">See your old booking request.</p>
                    </div>
                    <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-bar-chart-line"></i></div>
                        <h2 class="h5">Real time map</h2>
                        <p class="mb-0">Track track your location and the near charge point with filter and search.</p>
                    </div>
                    <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-shield-lock"></i></div>
                        <h2 class="h5">Account Settings</h2>
                        <p class="mb-0">Update your login details and manage your account securely.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php require('Views/template/footer.phtml') ?>
