<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title> <?php echo $view->pageTitle; ?></title>
    </head>
    
    <body>
        <h1>header</h1>
        <div class="continer">
        
            <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
                <ul class="nav navbar_default nav-stacked">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="login.php">Login</a></li>
                    <li><a href="signUp.php">Sign UP</a></li>
                </ul>
            </div>
        
        </div>
    </body>
</html>

